# Site settings
title: Shachar Mirkin
description: Personal website of Shachar Mirkin
baseurl: ""
url: "https://shacharmirkin.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Sass/SCSS settings
sass:
  sass_dir: assets/css
  style: compressed

author: Shachar Mirkin
#description: >- 
#  Shachar Mirkin's page

github_username: shacharmirkin

plugins:
  - jekyll-feed    # Creates an Atom feed (RSS) for your posts
  - jekyll-seo-tag # Adds metadata tags for SEO
  - jekyll-sass-converter


# Example (syntax might vary based on theme)
header_pages:
  - index.md # Or sometimes just '/'
  - snippets.md
  - research.md
  - contact.md
