name: Preview Site

on:
  push:
    branches-ignore:
      - main # or master, depending on your default branch name

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build --verbose

      - name: List built files
        run: |
          echo "==================== START OF BUILT FILES ===================="
          ls -R _site
          echo "==================== END OF BUILT FILES ===================="

      - name: Deploy preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          destination_dir: preview/${{ github.ref_name }}

      - name: Debug - List gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages
          git checkout gh-pages
          echo "==================== START OF GH-PAGES CONTENT ===================="
          ls -R preview
          echo "==================== END OF GH-PAGES CONTENT ===================="

      - name: Print preview URL
        run: |
          echo "==================== PREVIEW URL ===================="
          echo "https://shacharmirkin.github.io/preview/${{ github.ref_name }}/"
          echo "======================================================"

      - name: Find index.md
        run: |
          echo "==================== SEARCHING FOR INDEX.MD ===================="
          find . -name "index.md"
          echo "==================== END OF SEARCH ===================="

      - name: Display content of index file
        run: |
          echo "==================== CONTENT OF INDEX FILE ===================="
          cat index.*
          echo "==================== END OF INDEX FILE CONTENT ===================="

      - name: List _site directory
        run: |
          echo "==================== CONTENTS OF _SITE DIRECTORY ===================="
          ls -R _site
          echo "==================== END OF _SITE DIRECTORY LISTING ===================="
